[2024-10-24T22:51:39.381+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T22:51:39.398+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SetupETLtables.load manual__2024-10-24T22:51:37.577249+00:00 [queued]>
[2024-10-24T22:51:39.405+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SetupETLtables.load manual__2024-10-24T22:51:37.577249+00:00 [queued]>
[2024-10-24T22:51:39.408+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-24T22:51:39.415+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-10-24 22:51:37.577249+00:00
[2024-10-24T22:51:39.420+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-24T22:51:39.421+0000] {standard_task_runner.py:63} INFO - Started process 402 to run task
[2024-10-24T22:51:39.421+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'SetupETLtables', 'load', 'manual__2024-10-24T22:51:37.577249+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/etl_table_snowflake.py', '--cfg-path', '/tmp/tmp0qm36_p4']
[2024-10-24T22:51:39.422+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask load
[2024-10-24T22:51:39.457+0000] {task_command.py:426} INFO - Running <TaskInstance: SetupETLtables.load manual__2024-10-24T22:51:37.577249+00:00 [running]> on host 64c676815d01
[2024-10-24T22:51:39.508+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SetupETLtables' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T22:51:37.577249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T22:51:37.577249+00:00'
[2024-10-24T22:51:39.510+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T22:51:39.519+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-10-24T22:51:39.520+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.4-linuxkit-aarch64-with-glibc2.36
[2024-10-24T22:51:39.521+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-24T22:51:40.231+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-10-24T22:51:41.438+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-10-24T22:51:42.764+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-10-24T22:51:42.767+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-24T22:51:42.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-24T22:51:42.782+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=SetupETLtables, task_id=load, run_id=manual__2024-10-24T22:51:37.577249+00:00, execution_date=20241024T225137, start_date=20241024T225139, end_date=20241024T225142
[2024-10-24T22:51:42.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-24T22:51:42.835+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T22:51:42.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
