[2024-11-10T19:09:14.281+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T19:09:14.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SetupETLtables.load scheduled__2024-11-06T02:30:00+00:00 [queued]>
[2024-11-10T19:09:14.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SetupETLtables.load scheduled__2024-11-06T02:30:00+00:00 [queued]>
[2024-11-10T19:09:14.512+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T19:09:14.550+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-11-06 02:30:00+00:00
[2024-11-10T19:09:14.616+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'SetupETLtables', 'load', 'scheduled__2024-11-06T02:30:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/etl_table_snowflake.py', '--cfg-path', '/tmp/tmpikfpimbn']
[2024-11-10T19:09:14.638+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask load
[2024-11-10T19:09:14.670+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-10T19:09:14.677+0000] {standard_task_runner.py:63} INFO - Started process 246 to run task
[2024-11-10T19:09:14.879+0000] {task_command.py:426} INFO - Running <TaskInstance: SetupETLtables.load scheduled__2024-11-06T02:30:00+00:00 [running]> on host 599a8e9540bd
[2024-11-10T19:09:15.183+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SetupETLtables' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-06T02:30:00+00:00'
[2024-11-10T19:09:15.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T19:09:15.310+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-10T19:09:15.391+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.4-linuxkit-aarch64-with-glibc2.36
[2024-11-10T19:09:15.406+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-10T19:09:22.729+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-10T19:09:24.777+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-10T19:09:25.513+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-10T19:09:25.527+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-10T19:09:25.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T19:09:25.597+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=SetupETLtables, task_id=load, run_id=scheduled__2024-11-06T02:30:00+00:00, execution_date=20241106T023000, start_date=20241110T190914, end_date=20241110T190925
[2024-11-10T19:09:25.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-10T19:09:25.774+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T19:09:25.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
